### PR TITLE
Login-Signup Modal

### PR DESCRIPTION
**Pull request by CYCBrian**
Turned Login and Signup into modals.

Set up states to open and close modal in landing page

Converted employee signup and login to function as modals

Added a handleCloseModal function that will clear the forms and alerts

Added basic styles to modals

Added close button svg to forms to handleCloseModal and state handling

**Tried to make a close button from scratch but the &times: is always slighting skewed downwards, tried many solutions but none worked, replaced with a close button svg instead.

**The modals will prevent the user from interacting with anything outside of the modal unless the user clicks the close button, which should help with UX... maybe

**Something is overriding the css in the component folders. Idk if it's the styles from default tailwind library. Currently the big green button doesn't listen to css sheet on hover. There's also a slight box shadow or embossed effect on the form itself.

### CODE REVIEW

**Comment by CYCBrian** [comment]
Once again formatting the document made it seem like I did a lot more work...

**Comment by CYCBrian** [comment]
I'm also going to make the close button be position on the right upper corner after this push. I just thought maybe I should push something so ya'll don't think I'm dead.

**Comment by CYCBrian** [comment]
All work is a little janky rn. So time goes on I'll continue to improve it.

Most important is that to make everything responsive.

**Review by JohnM89 — APPROVED** [review]
Looks really good! Well done. Nice work on the close button and button sin general. I will take a look at the css override issue, maybe something in the tailwindplug definitions thats causing a conflict.. ill try to sort it out, thanks!

**Pull request merged**
